name: pterodactyl_mobile
description: Open-source Android client for controlling and monitoring Minecraft servers on any Pterodactyl panel.
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0b1116"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
